[package]
name = "vectordb-nodejs"
edition = "2021"
version = "0.0.0"
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.14", default-features = false, features = [
    "napi7",
    "async"
] }
napi-derive = "2.14"
vectordb = { path = "../rust/vectordb" }
lance.workspace = true

[build-dependencies]
napi-build = "2.1"

[profile.release]
lto = true
strip = "symbols"
